name: islamic_ai
description: Explore authentic Islamic books and receive AI-powered answers to
  your questions about Islam.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.5
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.4
  intl: ^0.17.0
  islamic_gpt:
    path: ./packages/islamic_gpt
  islamic_gpt_repository:
    path: ./packages/islamic_gpt_repository
  loading_animation_widget: ^1.2.0+4
  local_api:
    path: ./packages/local_api

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
